import SwiftUI

// MARK: - Brand Colors (constant across light/dark)

extension Color {
    // Primary brand
    static let pfPrimary = PFColorToken.actionPrimary
    static let pfPrimaryDark = PFColorToken.actionPrimaryStrong
    static let pfPrimaryLight = PFColorToken.statusCompleted

    // Semantic status (constant across modes)
    static let pfCompleted = PFColorToken.statusCompleted
    static let pfCheckedIn = PFColorToken.statusCheckedIn
    static let pfPending = PFColorToken.statusPending
    static let pfRejected = PFColorToken.statusRejected
}

// MARK: - Adaptive Surface Colors
// These are auto-generated by Xcode from Assets.xcassets color sets:
//   Color.pfBackground, Color.pfCard, Color.pfCardBorder,
//   Color.pfMapBackground, Color.pfText, Color.pfTextMuted, Color.pfInactive
// Use them directly as Color.pfBackground etc. — no manual wrappers needed.

// MARK: - Dimensions

enum PFRadius {
    static let card = PFRadiusToken.lg
    static let button = PFRadiusToken.xl
    static let badge = PFRadiusToken.full
    static let small = PFRadiusToken.md
}

enum PFSpacing {
    static let screenPadding = PFSpaceToken.space4
    static let cardPadding = PFSpaceToken.space3
    static let sectionGap = PFSpaceToken.space4
    static let itemGap = PFSpaceToken.space2
}
