import SwiftUI

// MARK: - Brand Colors (constant across light/dark)

extension Color {
    // Primary brand
    static let pfPrimary = Color(red: 34/255, green: 197/255, blue: 94/255)        // #22c55e
    static let pfPrimaryDark = Color(red: 22/255, green: 163/255, blue: 74/255)     // #16a34a
    static let pfPrimaryLight = Color(red: 134/255, green: 239/255, blue: 172/255)  // #86efac

    // Semantic status (constant across modes)
    static let pfCompleted = Color(red: 34/255, green: 197/255, blue: 94/255)       // #22c55e green
    static let pfCheckedIn = Color(red: 59/255, green: 130/255, blue: 246/255)      // #3b82f6 blue
    static let pfPending = Color(red: 245/255, green: 158/255, blue: 11/255)        // #f59e0b amber
    static let pfRejected = Color(red: 239/255, green: 68/255, blue: 68/255)        // #ef4444 red
}

// MARK: - Adaptive Surface Colors
// These are auto-generated by Xcode from Assets.xcassets color sets:
//   Color.pfBackground, Color.pfCard, Color.pfCardBorder,
//   Color.pfMapBackground, Color.pfText, Color.pfTextMuted, Color.pfInactive
// Use them directly as Color.pfBackground etc. — no manual wrappers needed.

// MARK: - Dimensions

enum PFRadius {
    static let card: CGFloat = 14
    static let button: CGFloat = 16
    static let badge: CGFloat = 20
    static let small: CGFloat = 10
}

enum PFSpacing {
    static let screenPadding: CGFloat = 16
    static let cardPadding: CGFloat = 12
    static let sectionGap: CGFloat = 16
    static let itemGap: CGFloat = 8
}
