// Brand derivations from the approved master mark. The master SVG is the only
// source; this module never rewrites it. Text outputs (TypeScript path module,
// favicon SVG, Android vector drawables) are regenerated byte-for-byte by
// generate.mjs. Raster exports come from brand-raster.py and are pinned by
// hash in design-system/brand/exports.json so drift against the master is
// detected by `generate.mjs --check` without requiring identical rasterizers.
import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

export const MASTER_RELATIVE = 'design-system/brand/pointfinder-mark.svg'
export const EXPORTS_MANIFEST_RELATIVE = 'design-system/brand/exports.json'
export const TAURI_ICON_MANIFEST_RELATIVE = 'design-system/brand/exports/tauri-icon.json'
/** Everything `tauri icon` writes; pinned by brand-tauri.mjs. */
export const TAURI_OUTPUT_DIRS = ['mobile/src-tauri/icons', 'mobile/src-tauri/gen/apple/Assets.xcassets/AppIcon.appiconset', ...['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi', 'anydpi-v26'].map((density) => `mobile/src-tauri/gen/android/app/src/main/res/mipmap-${density}`)]
/** Tauri emits ICNS image entries in varying order. Preserve their bytes but
 * sort the entries so the container can be pinned like every other export. */
export function normalizeIcns(bytes) {
  if (bytes.length < 8 || bytes.toString('ascii', 0, 4) !== 'icns' || bytes.readUInt32BE(4) !== bytes.length) {
    throw new Error('invalid ICNS container')
  }
  const entries = []
  for (let offset = 8; offset < bytes.length;) {
    if (offset + 8 > bytes.length) throw new Error('truncated ICNS entry')
    const length = bytes.readUInt32BE(offset + 4)
    if (length < 8 || offset + length > bytes.length) throw new Error('invalid ICNS entry length')
    entries.push(bytes.subarray(offset, offset + length))
    offset += length
  }
  return Buffer.concat([bytes.subarray(0, 8), ...entries.sort(Buffer.compare)])
}

/** Adaptive icon placement: the 512-unit master scaled into a 108 dp viewport.
 *  68 dp keeps the pointer's circumscribed circle (≈475 units) inside the 66 dp safe zone. */
export const ANDROID_ADAPTIVE = { viewport: 108, markSize: 68 }

const sha256 = (buffer) => createHash('sha256').update(buffer).digest('hex')

export async function readMaster(root) {
  const bytes = await readFile(resolve(root, MASTER_RELATIVE))
  const svg = bytes.toString('utf8')
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  if (viewBox !== '0 0 512 512') throw new Error(`unexpected master viewBox: ${viewBox}`)
  const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)]
  if (paths.length !== 1) throw new Error(`master must contain exactly one path, found ${paths.length}`)
  const fill = svg.match(/<path\b[^>]*\bfill="([^"]+)"/)?.[1]
  if (!fill) throw new Error('master path has no fill')
  const d = paths[0][1].replace(/\s+/g, ' ').trim()
  return { svg, d, fill: fill.toLowerCase(), viewBox, hash: sha256(bytes) }
}

/** `web/src/generated/brandMark.ts`: the only path data product code may consume. */
export function brandMarkModule(master, brandTokens) {
  return `// Generated from ${MASTER_RELATIVE}. Do not edit.
// Source sha256: ${master.hash}
/** Approved PointFinder mark: one filled path in a 512 × 512 viewBox, 380 × 380 solid bounds with a 66-unit inset. */
export const brandMark = {
  viewBox: ${JSON.stringify(master.viewBox)},
  path: ${JSON.stringify(master.d)},
  /** Artwork color of the master; UI must use the semantic brand tokens instead. */
  artworkColor: ${JSON.stringify(master.fill)},
  inset: 66,
  solidSize: 380,
  sourceHash: ${JSON.stringify(master.hash)},
} as const

/** Semantic brand roles, mirrored from tokens.json for non-CSS consumers (canvas, exports). */
export const brandColors = ${JSON.stringify(brandTokens, null, 2)} as const
`
}

/** Browser favicon: the same path, cropped to the solid bounds plus 20 units of clear space, with the
 *  one-color positive treatment for light tabs and the reversed treatment for dark tabs. */
export function faviconSvg(master, brandTokens) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="46 46 420 420" role="img" aria-label="PointFinder">
  <!-- Generated from ${MASTER_RELATIVE}. Do not edit. -->
  <style>path{fill:${brandTokens.light.mark}}@media (prefers-color-scheme:dark){path{fill:${brandTokens.dark.mark}}}</style>
  <path d="${master.d}"/>
</svg>
`
}

/** Android adaptive-icon foreground: the master centered in the 108 dp viewport. `fill` is a color reference. */
export function androidForegroundVector(master, fill) {
  const { viewport, markSize } = ANDROID_ADAPTIVE
  const scale = markSize / 512
  const offset = (viewport - markSize) / 2
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from ${MASTER_RELATIVE}. Do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${viewport}dp"
    android:height="${viewport}dp"
    android:viewportWidth="${viewport}"
    android:viewportHeight="${viewport}">
    <group
        android:scaleX="${scale}"
        android:scaleY="${scale}"
        android:translateX="${offset}"
        android:translateY="${offset}">
        <path
            android:fillColor="${fill}"
            android:pathData="${master.d}" />
    </group>
</vector>
`
}

export function androidAdaptiveIconXml({ background, foreground, monochrome }) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from ${MASTER_RELATIVE}. Do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="${background}" />
    <foreground android:drawable="${foreground}" />
    <monochrome android:drawable="${monochrome}" />
</adaptive-icon>
`
}

/** Compare checked-in raster and Tauri exports against the pinned manifest: the master bytes, the brand
 *  token values they were rendered with, and every output file. Returns human-readable problems. */
export async function verifyRasterExports(root, master, brandTokens) {
  const problems = []
  let manifest
  try { manifest = JSON.parse(await readFile(resolve(root, EXPORTS_MANIFEST_RELATIVE), 'utf8')) }
  catch { return [`missing ${EXPORTS_MANIFEST_RELATIVE}; run design-system/scripts/brand-raster.py`] }
  if (manifest.source?.sha256 !== master.hash) problems.push(`raster exports were made from a different master (${EXPORTS_MANIFEST_RELATIVE} source hash); run brand-raster.py`)
  if (JSON.stringify(manifest.source?.brandTokens) !== JSON.stringify(brandTokens)) problems.push(`raster exports were rendered with different color.brand token values; run brand-raster.py`)
  const compare = async (files, label) => {
    for (const [relative, expected] of Object.entries(files ?? {})) {
      const actual = await readFile(resolve(root, relative)).then(sha256).catch(() => null)
      if (actual === null) problems.push(`missing ${label}: ${relative}`)
      else if (actual !== expected) problems.push(`${label} differs from manifest: ${relative}`)
    }
  }
  await compare(manifest.files, 'raster export')
  if (!manifest.tauri) problems.push('Tauri icon sets are not pinned; run brand-tauri.mjs')
  else {
    if (manifest.tauri.inputSha256 !== manifest.files?.[TAURI_ICON_MANIFEST_RELATIVE]) problems.push('Tauri icon sets were built from a different tauri-icon.json; run brand-tauri.mjs')
    await compare(manifest.tauri.files, 'Tauri icon export')
  }
  return problems
}
