# Preserve the existing TeamSpeak 3 binary and data on the bind mount.
# No server upgrade, new license acceptance, or private data baked into image.
FROM ubuntu@sha256:224a1869083a311ef3f13648a154ba79832fbef6364d31493642ca03082da254
RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /teamspeak/teamspeak3-server_linux_amd64
USER 999:987
ENTRYPOINT ["/teamspeak/teamspeak3-server_linux_amd64/ts3server"]
