import XCTest
@testable import dbv_nfc_games

/// Cross-platform DTO contract tests for iOS.
///
/// Validates that iOS model structs can correctly decode the canonical JSON
/// snapshots generated by the backend. This catches DTO drift between
/// backend and iOS.
final class DtoContractTests: XCTestCase {

    // MARK: - Snapshot JSON strings
    // These match the canonical snapshots in contract-snapshots/ at the repo root.
    // Embedded as inline strings because Xcode test bundles cannot easily
    // reference files outside the project directory.
    //
    // IMPORTANT: These inline JSON strings MUST be kept in sync with the
    // canonical snapshot files at:
    //   <repo-root>/contract-snapshots/AuthResponse.json
    //   <repo-root>/contract-snapshots/PlayerAuthResponse.json
    //   <repo-root>/contract-snapshots/GameResponse.json
    //   <repo-root>/contract-snapshots/SubmissionResponse.json
    //   <repo-root>/contract-snapshots/BaseProgressResponse.json
    //   <repo-root>/contract-snapshots/LeaderboardEntry.json
    //
    // If the backend regenerates snapshots, update these inline strings to match.
    // The testInlineSnapshotKeysMatchExpectedContractStructure() test below
    // validates the JSON key structure to catch accidental divergence.

    private let authResponseJSON = """
    {
      "accessToken": "eyJhbGciOiJIUzI1NiJ9.test-access-token",
      "refreshToken": "eyJhbGciOiJIUzI1NiJ9.test-refresh-token",
      "user": {
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "email": "operator@example.com",
        "name": "Test Operator",
        "role": "operator",
        "createdAt": "2025-01-15T10:30:00Z"
      }
    }
    """.data(using: .utf8)!

    private let playerAuthResponseJSON = """
    {
      "token": "eyJhbGciOiJIUzI1NiJ9.test-player-token",
      "player": {
        "id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "displayName": "Scout Team Alpha",
        "deviceId": "ios-device-abc123"
      },
      "team": {
        "id": "c3d4e5f6-a7b8-9012-cdef-123456789012",
        "name": "Eagles",
        "color": "#FF5733"
      },
      "game": {
        "id": "d4e5f6a7-b8c9-0123-defa-234567890123",
        "name": "Forest Adventure",
        "description": "A scouting game in the forest",
        "status": "live",
        "tileSource": "osm-classic"
      }
    }
    """.data(using: .utf8)!

    private let gameResponseJSON = """
    {
      "id": "d4e5f6a7-b8c9-0123-defa-234567890123",
      "name": "Forest Adventure",
      "description": "A scouting game in the forest",
      "startDate": "2025-03-01T08:00:00Z",
      "endDate": "2025-03-01T18:00:00Z",
      "status": "live",
      "createdBy": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "operatorIds": [
        "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
      ],
      "uniformAssignment": false,
      "broadcastEnabled": true,
      "broadcastCode": "FOREST2025",
      "tileSource": "osm-classic"
    }
    """.data(using: .utf8)!

    private let submissionResponseJSON = """
    {
      "id": "e5f6a7b8-c9d0-1234-efab-345678901234",
      "teamId": "c3d4e5f6-a7b8-9012-cdef-123456789012",
      "challengeId": "f6a7b8c9-d0e1-2345-fabc-456789012345",
      "baseId": "a7b8c9d0-e1f2-3456-abcd-567890123456",
      "answer": "The answer is 42",
      "fileUrl": "/uploads/game1/photo.jpg",
      "fileUrls": [
        "/uploads/game1/photo.jpg",
        "/uploads/game1/photo2.jpg"
      ],
      "status": "approved",
      "submittedAt": "2025-03-01T10:30:00Z",
      "reviewedBy": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "feedback": "Great work!",
      "points": 100,
      "completionContent": "You found the hidden treasure!"
    }
    """.data(using: .utf8)!

    private let baseProgressResponseJSON = """
    {
      "baseId": "a7b8c9d0-e1f2-3456-abcd-567890123456",
      "baseName": "Forest Clearing",
      "lat": 47.3769,
      "lng": 8.5417,
      "nfcLinked": true,
      "status": "completed",
      "checkedInAt": "2025-03-01T09:15:00Z",
      "challengeId": "f6a7b8c9-d0e1-2345-fabc-456789012345",
      "submissionStatus": "approved"
    }
    """.data(using: .utf8)!

    private let leaderboardEntryJSON = """
    {
      "teamId": "c3d4e5f6-a7b8-9012-cdef-123456789012",
      "teamName": "Eagles",
      "color": "#FF5733",
      "points": 350,
      "completedChallenges": 5
    }
    """.data(using: .utf8)!

    // MARK: - Tests

    func testAuthResponse_decodesFromContractSnapshot() throws {
        let dto = try JSONDecoder().decode(OperatorAuthResponse.self, from: authResponseJSON)

        XCTAssertEqual(dto.accessToken, "eyJhbGciOiJIUzI1NiJ9.test-access-token")
        XCTAssertEqual(dto.refreshToken, "eyJhbGciOiJIUzI1NiJ9.test-refresh-token")
        XCTAssertEqual(dto.user.id, UUID(uuidString: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"))
        XCTAssertEqual(dto.user.email, "operator@example.com")
        XCTAssertEqual(dto.user.name, "Test Operator")
        XCTAssertEqual(dto.user.role, "operator")
    }

    func testPlayerAuthResponse_decodesFromContractSnapshot() throws {
        let dto = try JSONDecoder().decode(PlayerAuthResponse.self, from: playerAuthResponseJSON)

        XCTAssertEqual(dto.token, "eyJhbGciOiJIUzI1NiJ9.test-player-token")
        XCTAssertEqual(dto.player.id, UUID(uuidString: "b2c3d4e5-f6a7-8901-bcde-f12345678901"))
        XCTAssertEqual(dto.player.displayName, "Scout Team Alpha")
        XCTAssertEqual(dto.player.deviceId, "ios-device-abc123")
        XCTAssertEqual(dto.team.id, UUID(uuidString: "c3d4e5f6-a7b8-9012-cdef-123456789012"))
        XCTAssertEqual(dto.team.name, "Eagles")
        XCTAssertEqual(dto.team.color, "#FF5733")
        XCTAssertEqual(dto.game.id, UUID(uuidString: "d4e5f6a7-b8c9-0123-defa-234567890123"))
        XCTAssertEqual(dto.game.name, "Forest Adventure")
        XCTAssertEqual(dto.game.description, "A scouting game in the forest")
        XCTAssertEqual(dto.game.status, "live")
        XCTAssertEqual(dto.game.tileSource, "osm-classic")
    }

    func testGameResponse_decodesFromContractSnapshot() throws {
        let dto = try JSONDecoder().decode(Game.self, from: gameResponseJSON)

        XCTAssertEqual(dto.id, UUID(uuidString: "d4e5f6a7-b8c9-0123-defa-234567890123"))
        XCTAssertEqual(dto.name, "Forest Adventure")
        XCTAssertEqual(dto.description, "A scouting game in the forest")
        XCTAssertEqual(dto.status, "live")
        XCTAssertEqual(dto.tileSource, "osm-classic")
        XCTAssertEqual(dto.uniformAssignment, false)
        XCTAssertEqual(dto.broadcastEnabled, true)
        XCTAssertEqual(dto.broadcastCode, "FOREST2025")
        XCTAssertEqual(dto.startDate, "2025-03-01T08:00:00Z")
        XCTAssertEqual(dto.endDate, "2025-03-01T18:00:00Z")
        XCTAssertEqual(dto.createdBy, UUID(uuidString: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"))
        XCTAssertNotNil(dto.operatorIds)
        XCTAssertEqual(dto.operatorIds?.count, 1)
    }

    func testSubmissionResponse_decodesFromContractSnapshot() throws {
        let dto = try JSONDecoder().decode(SubmissionResponse.self, from: submissionResponseJSON)

        XCTAssertEqual(dto.id, UUID(uuidString: "e5f6a7b8-c9d0-1234-efab-345678901234"))
        XCTAssertEqual(dto.teamId, UUID(uuidString: "c3d4e5f6-a7b8-9012-cdef-123456789012"))
        XCTAssertEqual(dto.challengeId, UUID(uuidString: "f6a7b8c9-d0e1-2345-fabc-456789012345"))
        XCTAssertEqual(dto.baseId, UUID(uuidString: "a7b8c9d0-e1f2-3456-abcd-567890123456"))
        XCTAssertEqual(dto.answer, "The answer is 42")
        XCTAssertEqual(dto.fileUrl, "/uploads/game1/photo.jpg")
        XCTAssertNotNil(dto.fileUrls)
        XCTAssertEqual(dto.fileUrls?.count, 2)
        XCTAssertEqual(dto.status, "approved")
        XCTAssertEqual(dto.submittedAt, "2025-03-01T10:30:00Z")
        XCTAssertEqual(dto.reviewedBy, UUID(uuidString: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"))
        XCTAssertEqual(dto.feedback, "Great work!")
        XCTAssertEqual(dto.points, 100)
        XCTAssertEqual(dto.completionContent, "You found the hidden treasure!")
    }

    func testBaseProgressResponse_decodesFromContractSnapshot() throws {
        let dto = try JSONDecoder().decode(BaseProgress.self, from: baseProgressResponseJSON)

        XCTAssertEqual(dto.baseId, UUID(uuidString: "a7b8c9d0-e1f2-3456-abcd-567890123456"))
        XCTAssertEqual(dto.baseName, "Forest Clearing")
        XCTAssertEqual(dto.lat, 47.3769, accuracy: 0.0001)
        XCTAssertEqual(dto.lng, 8.5417, accuracy: 0.0001)
        XCTAssertTrue(dto.nfcLinked)
        XCTAssertEqual(dto.status, "completed")
        XCTAssertEqual(dto.checkedInAt, "2025-03-01T09:15:00Z")
        XCTAssertEqual(dto.challengeId, UUID(uuidString: "f6a7b8c9-d0e1-2345-fabc-456789012345"))
        XCTAssertEqual(dto.submissionStatus, "approved")
    }

    func testLeaderboardEntry_decodesFromContractSnapshot() throws {
        let dto = try JSONDecoder().decode(LeaderboardEntry.self, from: leaderboardEntryJSON)

        XCTAssertEqual(dto.teamId, UUID(uuidString: "c3d4e5f6-a7b8-9012-cdef-123456789012"))
        XCTAssertEqual(dto.teamName, "Eagles")
        XCTAssertEqual(dto.color, "#FF5733")
        XCTAssertEqual(dto.points, 350)
        XCTAssertEqual(dto.completedChallenges, 5)
    }

    // MARK: - Inline snapshot key structure validation
    //
    // This test validates that the inline JSON snapshots above contain the
    // expected top-level and nested key sets from the canonical contract
    // snapshots. If a snapshot is regenerated with new/renamed fields, this
    // test will fail, signaling the inline strings need updating.

    func testInlineSnapshotKeysMatchExpectedContractStructure() throws {
        // Helper to extract sorted keys from JSON data
        func topLevelKeys(_ data: Data) throws -> [String] {
            let obj = try JSONSerialization.jsonObject(with: data) as! [String: Any]
            return obj.keys.sorted()
        }
        func nestedKeys(_ data: Data, key: String) throws -> [String] {
            let obj = try JSONSerialization.jsonObject(with: data) as! [String: Any]
            guard let nested = obj[key] as? [String: Any] else { return [] }
            return nested.keys.sorted()
        }

        // AuthResponse: top-level keys and nested "user" keys
        let authKeys = try topLevelKeys(authResponseJSON)
        XCTAssertEqual(authKeys, ["accessToken", "refreshToken", "user"])
        let authUserKeys = try nestedKeys(authResponseJSON, key: "user")
        XCTAssertEqual(authUserKeys, ["createdAt", "email", "id", "name", "role"])

        // PlayerAuthResponse: top-level keys and nested keys
        let playerAuthKeys = try topLevelKeys(playerAuthResponseJSON)
        XCTAssertEqual(playerAuthKeys, ["game", "player", "team", "token"])
        let playerKeys = try nestedKeys(playerAuthResponseJSON, key: "player")
        XCTAssertEqual(playerKeys, ["deviceId", "displayName", "id"])

        // GameResponse: top-level keys
        let gameKeys = try topLevelKeys(gameResponseJSON)
        XCTAssertEqual(gameKeys, [
            "broadcastCode", "broadcastEnabled", "createdBy", "description",
            "endDate", "id", "name", "operatorIds", "startDate", "status",
            "tileSource", "uniformAssignment"
        ])

        // SubmissionResponse: top-level keys
        let submissionKeys = try topLevelKeys(submissionResponseJSON)
        XCTAssertEqual(submissionKeys, [
            "answer", "baseId", "challengeId", "completionContent", "feedback",
            "fileUrl", "fileUrls", "id", "points", "reviewedBy", "status",
            "submittedAt", "teamId"
        ])

        // BaseProgressResponse: top-level keys
        let baseProgressKeys = try topLevelKeys(baseProgressResponseJSON)
        XCTAssertEqual(baseProgressKeys, [
            "baseId", "baseName", "challengeId", "checkedInAt", "lat",
            "lng", "nfcLinked", "status", "submissionStatus"
        ])

        // LeaderboardEntry: top-level keys
        let leaderboardKeys = try topLevelKeys(leaderboardEntryJSON)
        XCTAssertEqual(leaderboardKeys, [
            "color", "completedChallenges", "points", "teamId", "teamName"
        ])
    }
}
